telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.chat.id=${TELEGRAM_CHAT_ID}

notion.api.token=${NOTION_API_TOKEN}
notion.database.id=${NOTION_DATABASE_ID}

groq.api.key=${GROQ_API_KEY}
groq.model.name=llama-3.1-8b-instant

server.port=${PORT:8080}